package io.gatling.liferay.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import io.gatling.liferay.model.Request;
import io.gatling.liferay.service.RequestLocalServiceUtil;

/**
 * The extended model base implementation for the Request service. Represents a row in the &quot;StressTool_Request&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RequestImpl
 * @see io.gatling.liferay.model.Request
 * @generated
 */
public abstract class RequestBaseImpl extends RequestModelImpl
    implements Request {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a request model instance should use the {@link Request} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RequestLocalServiceUtil.addRequest(this);
        } else {
            RequestLocalServiceUtil.updateRequest(this);
        }
    }
}
