package io.gatling.liferay.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import io.gatling.liferay.model.UrlRecord;
import io.gatling.liferay.service.UrlRecordLocalServiceUtil;

/**
 * The extended model base implementation for the UrlRecord service. Represents a row in the &quot;StressTool_UrlRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UrlRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UrlRecordImpl
 * @see io.gatling.liferay.model.UrlRecord
 * @generated
 */
public abstract class UrlRecordBaseImpl extends UrlRecordModelImpl
    implements UrlRecord {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a url record model instance should use the {@link UrlRecord} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UrlRecordLocalServiceUtil.addUrlRecord(this);
        } else {
            UrlRecordLocalServiceUtil.updateUrlRecord(this);
        }
    }
}
