/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Scenario service. Represents a row in the &quot;StressTool_Scenario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.ScenarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.ScenarioImpl}.
 * </p>
 *
 * @author sana
 * @see Scenario
 * @see com.liferay.sample.model.impl.ScenarioImpl
 * @see com.liferay.sample.model.impl.ScenarioModelImpl
 * @generated
 */
public interface ScenarioModel extends BaseModel<Scenario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a scenario model instance should use the {@link Scenario} interface instead.
	 */

	/**
	 * Returns the primary key of this scenario.
	 *
	 * @return the primary key of this scenario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this scenario.
	 *
	 * @param primaryKey the primary key of this scenario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the scenario_id of this scenario.
	 *
	 * @return the scenario_id of this scenario
	 */
	public long getScenario_id();

	/**
	 * Sets the scenario_id of this scenario.
	 *
	 * @param scenario_id the scenario_id of this scenario
	 */
	public void setScenario_id(long scenario_id);

	/**
	 * Returns the name of this scenario.
	 *
	 * @return the name of this scenario
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this scenario.
	 *
	 * @param name the name of this scenario
	 */
	public void setName(String name);

	/**
	 * Returns the group_id of this scenario.
	 *
	 * @return the group_id of this scenario
	 */
	public long getGroup_id();

	/**
	 * Sets the group_id of this scenario.
	 *
	 * @param group_id the group_id of this scenario
	 */
	public void setGroup_id(long group_id);

	/**
	 * Returns the simulation_id of this scenario.
	 *
	 * @return the simulation_id of this scenario
	 */
	public long getSimulation_id();

	/**
	 * Sets the simulation_id of this scenario.
	 *
	 * @param simulation_id the simulation_id of this scenario
	 */
	public void setSimulation_id(long simulation_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Scenario scenario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Scenario> toCacheModel();

	@Override
	public Scenario toEscapedModel();

	@Override
	public Scenario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}