/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.excilys.liferay.gatling.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LinkUsecasePortletStress service. Represents a row in the &quot;StressTool_LinkUsecasePortletStress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.excilys.liferay.gatling.model.impl.LinkUsecasePortletStressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.excilys.liferay.gatling.model.impl.LinkUsecasePortletStressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LinkUsecasePortletStress
 * @see com.excilys.liferay.gatling.model.impl.LinkUsecasePortletStressImpl
 * @see com.excilys.liferay.gatling.model.impl.LinkUsecasePortletStressModelImpl
 * @generated
 */
public interface LinkUsecasePortletStressModel extends BaseModel<LinkUsecasePortletStress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a link usecase portlet stress model instance should use the {@link LinkUsecasePortletStress} interface instead.
	 */

	/**
	 * Returns the primary key of this link usecase portlet stress.
	 *
	 * @return the primary key of this link usecase portlet stress
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this link usecase portlet stress.
	 *
	 * @param primaryKey the primary key of this link usecase portlet stress
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the link usecase portlet stress ID of this link usecase portlet stress.
	 *
	 * @return the link usecase portlet stress ID of this link usecase portlet stress
	 */
	public long getLinkUsecasePortletStressId();

	/**
	 * Sets the link usecase portlet stress ID of this link usecase portlet stress.
	 *
	 * @param linkUsecasePortletStressId the link usecase portlet stress ID of this link usecase portlet stress
	 */
	public void setLinkUsecasePortletStressId(long linkUsecasePortletStressId);

	/**
	 * Returns the portlet stress ID of this link usecase portlet stress.
	 *
	 * @return the portlet stress ID of this link usecase portlet stress
	 */
	public long getPortletStressId();

	/**
	 * Sets the portlet stress ID of this link usecase portlet stress.
	 *
	 * @param portletStressId the portlet stress ID of this link usecase portlet stress
	 */
	public void setPortletStressId(long portletStressId);

	/**
	 * Returns the usecase ID of this link usecase portlet stress.
	 *
	 * @return the usecase ID of this link usecase portlet stress
	 */
	public long getUsecaseId();

	/**
	 * Sets the usecase ID of this link usecase portlet stress.
	 *
	 * @param usecaseId the usecase ID of this link usecase portlet stress
	 */
	public void setUsecaseId(long usecaseId);

	/**
	 * Returns the weight of this link usecase portlet stress.
	 *
	 * @return the weight of this link usecase portlet stress
	 */
	public double getWeight();

	/**
	 * Sets the weight of this link usecase portlet stress.
	 *
	 * @param weight the weight of this link usecase portlet stress
	 */
	public void setWeight(double weight);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LinkUsecasePortletStress linkUsecasePortletStress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LinkUsecasePortletStress> toCacheModel();

	@Override
	public LinkUsecasePortletStress toEscapedModel();

	@Override
	public LinkUsecasePortletStress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}