/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.excilys.liferay.gatling.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RecordPortlet service. Represents a row in the &quot;StressTool_RecordPortlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.excilys.liferay.gatling.model.impl.RecordPortletModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.excilys.liferay.gatling.model.impl.RecordPortletImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecordPortlet
 * @see com.excilys.liferay.gatling.model.impl.RecordPortletImpl
 * @see com.excilys.liferay.gatling.model.impl.RecordPortletModelImpl
 * @generated
 */
public interface RecordPortletModel extends BaseModel<RecordPortlet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a record portlet model instance should use the {@link RecordPortlet} interface instead.
	 */

	/**
	 * Returns the primary key of this record portlet.
	 *
	 * @return the primary key of this record portlet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this record portlet.
	 *
	 * @param primaryKey the primary key of this record portlet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the record portlet ID of this record portlet.
	 *
	 * @return the record portlet ID of this record portlet
	 */
	public long getRecordPortletId();

	/**
	 * Sets the record portlet ID of this record portlet.
	 *
	 * @param recordPortletId the record portlet ID of this record portlet
	 */
	public void setRecordPortletId(long recordPortletId);

	/**
	 * Returns the portlet ID of this record portlet.
	 *
	 * @return the portlet ID of this record portlet
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this record portlet.
	 *
	 * @param portletId the portlet ID of this record portlet
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the state of this record portlet.
	 *
	 * @return the state of this record portlet
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this record portlet.
	 *
	 * @param state the state of this record portlet
	 */
	public void setState(String state);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RecordPortlet recordPortlet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RecordPortlet> toCacheModel();

	@Override
	public RecordPortlet toEscapedModel();

	@Override
	public RecordPortlet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}