/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.excilys.liferay.gatling.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UrlUsecase service. Represents a row in the &quot;StressTool_UrlUsecase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.excilys.liferay.gatling.model.impl.UrlUsecaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.excilys.liferay.gatling.model.impl.UrlUsecaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UrlUsecase
 * @see com.excilys.liferay.gatling.model.impl.UrlUsecaseImpl
 * @see com.excilys.liferay.gatling.model.impl.UrlUsecaseModelImpl
 * @generated
 */
public interface UrlUsecaseModel extends BaseModel<UrlUsecase> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a url usecase model instance should use the {@link UrlUsecase} interface instead.
	 */

	/**
	 * Returns the primary key of this url usecase.
	 *
	 * @return the primary key of this url usecase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this url usecase.
	 *
	 * @param primaryKey the primary key of this url usecase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the url usecase ID of this url usecase.
	 *
	 * @return the url usecase ID of this url usecase
	 */
	public long getUrlUsecaseId();

	/**
	 * Sets the url usecase ID of this url usecase.
	 *
	 * @param urlUsecaseId the url usecase ID of this url usecase
	 */
	public void setUrlUsecaseId(long urlUsecaseId);

	/**
	 * Returns the usecase ID of this url usecase.
	 *
	 * @return the usecase ID of this url usecase
	 */
	public long getUsecaseId();

	/**
	 * Sets the usecase ID of this url usecase.
	 *
	 * @param usecaseId the usecase ID of this url usecase
	 */
	public void setUsecaseId(long usecaseId);

	/**
	 * Returns the url of this url usecase.
	 *
	 * @return the url of this url usecase
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this url usecase.
	 *
	 * @param url the url of this url usecase
	 */
	public void setUrl(String url);

	/**
	 * Returns the order of this url usecase.
	 *
	 * @return the order of this url usecase
	 */
	public int getOrder();

	/**
	 * Sets the order of this url usecase.
	 *
	 * @param order the order of this url usecase
	 */
	public void setOrder(int order);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UrlUsecase urlUsecase);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UrlUsecase> toCacheModel();

	@Override
	public UrlUsecase toEscapedModel();

	@Override
	public UrlUsecase toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}