/**
 * Copyright 2011-2016 GatlingCorp (http://gatling.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.gatling.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SiteMap service. Represents a row in the &quot;StressTool_SiteMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link io.gatling.liferay.model.impl.SiteMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link io.gatling.liferay.model.impl.SiteMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteMap
 * @see io.gatling.liferay.model.impl.SiteMapImpl
 * @see io.gatling.liferay.model.impl.SiteMapModelImpl
 * @generated
 */
public interface SiteMapModel extends BaseModel<SiteMap> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a site map model instance should use the {@link SiteMap} interface instead.
     */

    /**
     * Returns the primary key of this site map.
     *
     * @return the primary key of this site map
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this site map.
     *
     * @param primaryKey the primary key of this site map
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the site map ID of this site map.
     *
     * @return the site map ID of this site map
     */
    public long getSiteMapId();

    /**
     * Sets the site map ID of this site map.
     *
     * @param siteMapId the site map ID of this site map
     */
    public void setSiteMapId(long siteMapId);

    /**
     * Returns the name of this site map.
     *
     * @return the name of this site map
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this site map.
     *
     * @param name the name of this site map
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(SiteMap siteMap);

    @Override
    public int hashCode();

    @Override
    public CacheModel<SiteMap> toCacheModel();

    @Override
    public SiteMap toEscapedModel();

    @Override
    public SiteMap toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
