/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.RecordPortlet;
import com.excilys.liferay.gatling.service.RecordPortletLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the RecordPortlet service. Represents a row in the &quot;StressTool_RecordPortlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RecordPortletImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecordPortletImpl
 * @see com.excilys.liferay.gatling.model.RecordPortlet
 * @generated
 */
public abstract class RecordPortletBaseImpl extends RecordPortletModelImpl
	implements RecordPortlet {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a record portlet model instance should use the {@link RecordPortlet} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RecordPortletLocalServiceUtil.addRecordPortlet(this);
		}
		else {
			RecordPortletLocalServiceUtil.updateRecordPortlet(this);
		}
	}
}