/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.Usecase;
import com.excilys.liferay.gatling.model.UsecaseModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Usecase service. Represents a row in the &quot;StressTool_Usecase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.excilys.liferay.gatling.model.UsecaseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsecaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UsecaseImpl
 * @see com.excilys.liferay.gatling.model.Usecase
 * @see com.excilys.liferay.gatling.model.UsecaseModel
 * @generated
 */
public class UsecaseModelImpl extends BaseModelImpl<Usecase>
	implements UsecaseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a usecase model instance should use the {@link com.excilys.liferay.gatling.model.Usecase} interface instead.
	 */
	public static final String TABLE_NAME = "StressTool_Usecase";
	public static final Object[][] TABLE_COLUMNS = {
			{ "usecaseId", Types.BIGINT },
			{ "portletId", Types.BIGINT },
			{ "versionPortlet", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table StressTool_Usecase (usecaseId LONG not null primary key,portletId LONG,versionPortlet LONG,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table StressTool_Usecase";
	public static final String ORDER_BY_JPQL = " ORDER BY usecase.usecaseId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY StressTool_Usecase.usecaseId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.excilys.liferay.gatling.model.Usecase"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.excilys.liferay.gatling.model.Usecase"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.excilys.liferay.gatling.model.Usecase"));

	public UsecaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _usecaseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUsecaseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _usecaseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Usecase.class;
	}

	@Override
	public String getModelClassName() {
		return Usecase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("usecaseId", getUsecaseId());
		attributes.put("portletId", getPortletId());
		attributes.put("versionPortlet", getVersionPortlet());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long usecaseId = (Long)attributes.get("usecaseId");

		if (usecaseId != null) {
			setUsecaseId(usecaseId);
		}

		Long portletId = (Long)attributes.get("portletId");

		if (portletId != null) {
			setPortletId(portletId);
		}

		Long versionPortlet = (Long)attributes.get("versionPortlet");

		if (versionPortlet != null) {
			setVersionPortlet(versionPortlet);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public long getUsecaseId() {
		return _usecaseId;
	}

	@Override
	public void setUsecaseId(long usecaseId) {
		_usecaseId = usecaseId;
	}

	@Override
	public long getPortletId() {
		return _portletId;
	}

	@Override
	public void setPortletId(long portletId) {
		_portletId = portletId;
	}

	@Override
	public long getVersionPortlet() {
		return _versionPortlet;
	}

	@Override
	public void setVersionPortlet(long versionPortlet) {
		_versionPortlet = versionPortlet;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Usecase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Usecase toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Usecase)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UsecaseImpl usecaseImpl = new UsecaseImpl();

		usecaseImpl.setUsecaseId(getUsecaseId());
		usecaseImpl.setPortletId(getPortletId());
		usecaseImpl.setVersionPortlet(getVersionPortlet());
		usecaseImpl.setName(getName());

		usecaseImpl.resetOriginalValues();

		return usecaseImpl;
	}

	@Override
	public int compareTo(Usecase usecase) {
		long primaryKey = usecase.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Usecase)) {
			return false;
		}

		Usecase usecase = (Usecase)obj;

		long primaryKey = usecase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Usecase> toCacheModel() {
		UsecaseCacheModel usecaseCacheModel = new UsecaseCacheModel();

		usecaseCacheModel.usecaseId = getUsecaseId();

		usecaseCacheModel.portletId = getPortletId();

		usecaseCacheModel.versionPortlet = getVersionPortlet();

		usecaseCacheModel.name = getName();

		String name = usecaseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			usecaseCacheModel.name = null;
		}

		return usecaseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{usecaseId=");
		sb.append(getUsecaseId());
		sb.append(", portletId=");
		sb.append(getPortletId());
		sb.append(", versionPortlet=");
		sb.append(getVersionPortlet());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.excilys.liferay.gatling.model.Usecase");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>usecaseId</column-name><column-value><![CDATA[");
		sb.append(getUsecaseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portletId</column-name><column-value><![CDATA[");
		sb.append(getPortletId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionPortlet</column-name><column-value><![CDATA[");
		sb.append(getVersionPortlet());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Usecase.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Usecase.class
		};
	private long _usecaseId;
	private long _portletId;
	private long _versionPortlet;
	private String _name;
	private Usecase _escapedModel;
}