package io.gatling.liferay.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ProcessScenarioLink service. Represents a row in the &quot;StressTool_ProcessScenarioLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link io.gatling.liferay.model.impl.ProcessScenarioLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link io.gatling.liferay.model.impl.ProcessScenarioLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProcessScenarioLink
 * @see io.gatling.liferay.model.impl.ProcessScenarioLinkImpl
 * @see io.gatling.liferay.model.impl.ProcessScenarioLinkModelImpl
 * @generated
 */
public interface ProcessScenarioLinkModel extends BaseModel<ProcessScenarioLink> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a process scenario link model instance should use the {@link ProcessScenarioLink} interface instead.
     */

    /**
     * Returns the primary key of this process scenario link.
     *
     * @return the primary key of this process scenario link
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this process scenario link.
     *
     * @param primaryKey the primary key of this process scenario link
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the psl_id of this process scenario link.
     *
     * @return the psl_id of this process scenario link
     */
    public long getPsl_id();

    /**
     * Sets the psl_id of this process scenario link.
     *
     * @param psl_id the psl_id of this process scenario link
     */
    public void setPsl_id(long psl_id);

    /**
     * Returns the process_id of this process scenario link.
     *
     * @return the process_id of this process scenario link
     */
    public long getProcess_id();

    /**
     * Sets the process_id of this process scenario link.
     *
     * @param process_id the process_id of this process scenario link
     */
    public void setProcess_id(long process_id);

    /**
     * Returns the scenario_id of this process scenario link.
     *
     * @return the scenario_id of this process scenario link
     */
    public long getScenario_id();

    /**
     * Sets the scenario_id of this process scenario link.
     *
     * @param scenario_id the scenario_id of this process scenario link
     */
    public void setScenario_id(long scenario_id);

    /**
     * Returns the order of this process scenario link.
     *
     * @return the order of this process scenario link
     */
    public int getOrder();

    /**
     * Sets the order of this process scenario link.
     *
     * @param order the order of this process scenario link
     */
    public void setOrder(int order);

    /**
     * Returns the pause of this process scenario link.
     *
     * @return the pause of this process scenario link
     */
    public int getPause();

    /**
     * Sets the pause of this process scenario link.
     *
     * @param pause the pause of this process scenario link
     */
    public void setPause(int pause);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ProcessScenarioLink processScenarioLink);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ProcessScenarioLink> toCacheModel();

    @Override
    public ProcessScenarioLink toEscapedModel();

    @Override
    public ProcessScenarioLink toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
