package io.gatling.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Record service. Represents a row in the &quot;StressTool_Record&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link io.gatling.liferay.model.impl.RecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link io.gatling.liferay.model.impl.RecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Record
 * @see io.gatling.liferay.model.impl.RecordImpl
 * @see io.gatling.liferay.model.impl.RecordModelImpl
 * @generated
 */
public interface RecordModel extends BaseModel<Record> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a record model instance should use the {@link Record} interface instead.
     */

    /**
     * Returns the primary key of this record.
     *
     * @return the primary key of this record
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this record.
     *
     * @param primaryKey the primary key of this record
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the record ID of this record.
     *
     * @return the record ID of this record
     */
    public long getRecordId();

    /**
     * Sets the record ID of this record.
     *
     * @param recordId the record ID of this record
     */
    public void setRecordId(long recordId);

    /**
     * Returns the portlet ID of this record.
     *
     * @return the portlet ID of this record
     */
    @AutoEscape
    public String getPortletId();

    /**
     * Sets the portlet ID of this record.
     *
     * @param portletId the portlet ID of this record
     */
    public void setPortletId(String portletId);

    /**
     * Returns the version portlet of this record.
     *
     * @return the version portlet of this record
     */
    @AutoEscape
    public String getVersionPortlet();

    /**
     * Sets the version portlet of this record.
     *
     * @param versionPortlet the version portlet of this record
     */
    public void setVersionPortlet(String versionPortlet);

    /**
     * Returns the name of this record.
     *
     * @return the name of this record
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this record.
     *
     * @param name the name of this record
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Record record);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Record> toCacheModel();

    @Override
    public Record toEscapedModel();

    @Override
    public Record toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
