package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.FormParam;
import com.excilys.liferay.gatling.service.FormParamLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the FormParam service. Represents a row in the &quot;StressTool_FormParam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormParamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormParamImpl
 * @see com.excilys.liferay.gatling.model.FormParam
 * @generated
 */
public abstract class FormParamBaseImpl extends FormParamModelImpl
    implements FormParam {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a form param model instance should use the {@link FormParam} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FormParamLocalServiceUtil.addFormParam(this);
        } else {
            FormParamLocalServiceUtil.updateFormParam(this);
        }
    }
}
