package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.LinkProcessRecord;
import com.excilys.liferay.gatling.service.LinkProcessRecordLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LinkProcessRecord service. Represents a row in the &quot;StressTool_LinkProcessRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinkProcessRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LinkProcessRecordImpl
 * @see com.excilys.liferay.gatling.model.LinkProcessRecord
 * @generated
 */
public abstract class LinkProcessRecordBaseImpl
    extends LinkProcessRecordModelImpl implements LinkProcessRecord {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a link process record model instance should use the {@link LinkProcessRecord} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LinkProcessRecordLocalServiceUtil.addLinkProcessRecord(this);
        } else {
            LinkProcessRecordLocalServiceUtil.updateLinkProcessRecord(this);
        }
    }
}
