package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.Login;
import com.excilys.liferay.gatling.service.LoginLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Login service. Represents a row in the &quot;StressTool_Login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoginImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoginImpl
 * @see com.excilys.liferay.gatling.model.Login
 * @generated
 */
public abstract class LoginBaseImpl extends LoginModelImpl implements Login {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a login model instance should use the {@link Login} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LoginLocalServiceUtil.addLogin(this);
        } else {
            LoginLocalServiceUtil.updateLogin(this);
        }
    }
}
