package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.SiteMap;
import com.excilys.liferay.gatling.service.SiteMapLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SiteMap service. Represents a row in the &quot;StressTool_SiteMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SiteMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteMapImpl
 * @see com.excilys.liferay.gatling.model.SiteMap
 * @generated
 */
public abstract class SiteMapBaseImpl extends SiteMapModelImpl
    implements SiteMap {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a site map model instance should use the {@link SiteMap} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SiteMapLocalServiceUtil.addSiteMap(this);
        } else {
            SiteMapLocalServiceUtil.updateSiteMap(this);
        }
    }
}
