package com.excilys.liferay.gatling.model.impl;

import com.excilys.liferay.gatling.model.UrlSiteMap;
import com.excilys.liferay.gatling.service.UrlSiteMapLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the UrlSiteMap service. Represents a row in the &quot;StressTool_UrlSiteMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UrlSiteMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UrlSiteMapImpl
 * @see com.excilys.liferay.gatling.model.UrlSiteMap
 * @generated
 */
public abstract class UrlSiteMapBaseImpl extends UrlSiteMapModelImpl
    implements UrlSiteMap {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a url site map model instance should use the {@link UrlSiteMap} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UrlSiteMapLocalServiceUtil.addUrlSiteMap(this);
        } else {
            UrlSiteMapLocalServiceUtil.updateUrlSiteMap(this);
        }
    }
}
