/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.sample.model.Scenario;
import com.liferay.sample.model.ScenarioModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Scenario service. Represents a row in the &quot;StressTool_Scenario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.sample.model.ScenarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScenarioImpl}.
 * </p>
 *
 * @author sana
 * @see ScenarioImpl
 * @see com.liferay.sample.model.Scenario
 * @see com.liferay.sample.model.ScenarioModel
 * @generated
 */
public class ScenarioModelImpl extends BaseModelImpl<Scenario>
	implements ScenarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a scenario model instance should use the {@link com.liferay.sample.model.Scenario} interface instead.
	 */
	public static final String TABLE_NAME = "StressTool_Scenario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scenario_id", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "group_id", Types.BIGINT },
			{ "simulation_id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table StressTool_Scenario (scenario_id LONG not null primary key,name VARCHAR(75) null,group_id LONG,simulation_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table StressTool_Scenario";
	public static final String ORDER_BY_JPQL = " ORDER BY scenario.scenario_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY StressTool_Scenario.scenario_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.sample.model.Scenario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.sample.model.Scenario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.sample.model.Scenario"),
			true);
	public static long SIMULATION_ID_COLUMN_BITMASK = 1L;
	public static long SCENARIO_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.sample.model.Scenario"));

	public ScenarioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scenario_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScenario_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scenario_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Scenario.class;
	}

	@Override
	public String getModelClassName() {
		return Scenario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scenario_id", getScenario_id());
		attributes.put("name", getName());
		attributes.put("group_id", getGroup_id());
		attributes.put("simulation_id", getSimulation_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scenario_id = (Long)attributes.get("scenario_id");

		if (scenario_id != null) {
			setScenario_id(scenario_id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Long group_id = (Long)attributes.get("group_id");

		if (group_id != null) {
			setGroup_id(group_id);
		}

		Long simulation_id = (Long)attributes.get("simulation_id");

		if (simulation_id != null) {
			setSimulation_id(simulation_id);
		}
	}

	@Override
	public long getScenario_id() {
		return _scenario_id;
	}

	@Override
	public void setScenario_id(long scenario_id) {
		_scenario_id = scenario_id;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public long getGroup_id() {
		return _group_id;
	}

	@Override
	public void setGroup_id(long group_id) {
		_group_id = group_id;
	}

	@Override
	public long getSimulation_id() {
		return _simulation_id;
	}

	@Override
	public void setSimulation_id(long simulation_id) {
		_columnBitmask |= SIMULATION_ID_COLUMN_BITMASK;

		if (!_setOriginalSimulation_id) {
			_setOriginalSimulation_id = true;

			_originalSimulation_id = _simulation_id;
		}

		_simulation_id = simulation_id;
	}

	public long getOriginalSimulation_id() {
		return _originalSimulation_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Scenario.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Scenario toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Scenario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScenarioImpl scenarioImpl = new ScenarioImpl();

		scenarioImpl.setScenario_id(getScenario_id());
		scenarioImpl.setName(getName());
		scenarioImpl.setGroup_id(getGroup_id());
		scenarioImpl.setSimulation_id(getSimulation_id());

		scenarioImpl.resetOriginalValues();

		return scenarioImpl;
	}

	@Override
	public int compareTo(Scenario scenario) {
		long primaryKey = scenario.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Scenario)) {
			return false;
		}

		Scenario scenario = (Scenario)obj;

		long primaryKey = scenario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ScenarioModelImpl scenarioModelImpl = this;

		scenarioModelImpl._originalSimulation_id = scenarioModelImpl._simulation_id;

		scenarioModelImpl._setOriginalSimulation_id = false;

		scenarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Scenario> toCacheModel() {
		ScenarioCacheModel scenarioCacheModel = new ScenarioCacheModel();

		scenarioCacheModel.scenario_id = getScenario_id();

		scenarioCacheModel.name = getName();

		String name = scenarioCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			scenarioCacheModel.name = null;
		}

		scenarioCacheModel.group_id = getGroup_id();

		scenarioCacheModel.simulation_id = getSimulation_id();

		return scenarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{scenario_id=");
		sb.append(getScenario_id());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", group_id=");
		sb.append(getGroup_id());
		sb.append(", simulation_id=");
		sb.append(getSimulation_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.sample.model.Scenario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scenario_id</column-name><column-value><![CDATA[");
		sb.append(getScenario_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>group_id</column-name><column-value><![CDATA[");
		sb.append(getGroup_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>simulation_id</column-name><column-value><![CDATA[");
		sb.append(getSimulation_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Scenario.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Scenario.class
		};
	private long _scenario_id;
	private String _name;
	private long _group_id;
	private long _simulation_id;
	private long _originalSimulation_id;
	private boolean _setOriginalSimulation_id;
	private long _columnBitmask;
	private Scenario _escapedModel;
}